board/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'board'

urlpatterns = [
    path('create_board/', views.board, name='create_board'),
    path('board_detail/<int:board_id>/', views.read, name='board_detail'),
    path('board_edit/<int:pk>', views.boardEdit, name='edit'),
    path('delete/<int:pk>', views.boardDelete, name='delete'),
    path('comment_create/<int:pk>/', views.comment_create, name='comment_create'),
    path('comments/<int:board_pk>/delete/<int:comment_pk>/', views.comment_delete, name='comments_delete'),   
    path('board_list/', views.boardList, name = 'board_list'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from homemain import views

urlpatterns = [
    path('admin/', admin.site.urls) ,
    path('accounts/', include('accounts.urls')) ,
    path('user_inform/', include('user_inform.urls')) ,
    path('board/', include('board.urls')) ,
    path('index/', views.index, name='index'),  # '/' 에 해당되는 path
    #path('board_list/', views.boardList),
]

user_inform/urls.py
from django.urls import path
from . import views

app_name = 'user_inform'

urlpatterns = [
   #path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('',views.information,name='information') ,
    path('modifyinform/',views.profile_update_view, name='profile_update') ,
    path('modifypw/',views.password_edit_view, name='password_edit') ,
]

user_inform/models.py
from django.db import models

# Create your models here.

user_inform/forms.py
from django.contrib.auth.forms import PasswordChangeForm,UserChangeForm
from django import forms
from accounts.models import Users
class CustomPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super(CustomPasswordChangeForm, self).__init__(*args, **kwargs)
        self.fields['old_password'].label = '기존 비밀번호'
        self.fields['old_password'].widget.attrs.update({
            'class': 'form-control',
            'autofocus': False,
        })
        self.fields['new_password1'].label = '새 비밀번호'
        self.fields['new_password1'].widget.attrs.update({
            'class': 'form-control',
        })
        self.fields['new_password2'].label = '새 비밀번호 확인'
        self.fields['new_password2'].widget.attrs.update({
            'class': 'form-control',
        })


#회원정보 수정 폼
class CustomCsUserChangeForm(UserChangeForm):
    password = None              
    name = forms.CharField(label='이름', widget=forms.TextInput(
        attrs={'class': 'form-control', 'maxlength':'8',}), 
    )        
    nickname = forms.CharField(label='닉네임', widget=forms.TextInput(
        attrs={'class': 'form-control', 'maxlength':'8',}), 
    )        
    class Meta:
        # 변경 안되는 필드들은 메타 데이터에 표시하지 않는다
        model = Users()
        fields = [ 'name', 'nickname']

user_inform/views.py
# Create your views here.
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import render,redirect
from django.contrib.auth import update_session_auth_hash,logout
from django.views.decorators.http import require_http_methods
from .forms import CustomPasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from .forms import CustomCsUserChangeForm


# Create your views here.
def information(request):
    return render(request,'user_inform/information.html',{})


    
def profile_update_view(request):
    if request.method == 'POST':
        user_change_form = CustomCsUserChangeForm(request.POST, instance = request.user)

        if user_change_form.is_valid():
            user_change_form.save()
            messages.success(request, '회원정보가 수정되었습니다.')
            return redirect('user_inform:information')
    else:
        user_change_form = CustomCsUserChangeForm(instance = request.user)

        return render(request, 'user_inform/modifyinform.html', {'user_change_form':user_change_form})
    

@login_required
def password_edit_view(request):
    if request.method == 'POST':
        password_change_form = CustomPasswordChangeForm(request.user, request.POST)
        if password_change_form.is_valid():
            user = password_change_form.save()
            update_session_auth_hash(request, user)
            storage = messages.get_messages(request)
            storage.used = True  # 이전 메시지를 모두 소비하여 삭제합니다.
            messages.success(request, "비밀번호를 성공적으로 변경하였습니다. 다시 로그인 해주세요")
            logout(request)
            return redirect('accounts:login')
            # return redirect('user_inform:information')
    else:
        password_change_form = CustomPasswordChangeForm(request.user)
    
    # messages.get_messages(request)
    return render(request, 'user_inform/modifypw.html', {'password_change_form':password_change_form})

templates/user_inform/information.html
{% extends "base.html" %}

{% block content %}
<head>
    <title>내 정보</title>
</head>
<style>
.body {
    background-color: mediumturquoise;
}

.table {
    margin-bottom: 0;
}

hr {
    margin-top: 40px;
    margin-bottom: 40px;
    border: 0;
}

.card-body {
    background-color: #fff;
    padding: 20px;
    border-radius: 10px; 
}

.card-header {
        background-color: whitesmoke;
        border-bottom: 5px solid whitesmoke;
        padding-top: 14px;
    }

.card {
  width: 500px;
  height: auto;
  padding: 0;
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.2);
  border-radius: 10px;
}

    .profile_title {
        font-weight: bold;
        color: black;
        background-color: grey;
    }

    .profile_content {
        color: #666;
    }

    .btn-profile-update {
        position: absolute;
    right: 300px; /* 사이드 바 버튼과의 거리 조절 */
   
    top: 400px;   /* 사이드 바 버튼과의 거리 조절 */
    /* left: 500px; */
        width: 200px; /* 버튼 너비 */
        height: 50px; /* 버튼 높이 */
    background-color: #111;
    color: white;
    display: flex;
    justify-content: center; 
    align-items: center;
    padding: 10px 20px;
    border: none;
    cursor: pointer;
    z-index: 1002; /* 새 글 작성 버튼 위에 위치하도록 z-index 값을 높임 */
    box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;
    }

    .btn-profile-update:hover {
        background-color: mediumaquamarine; /* 마우스 호버 시 배경색을 검정색으로 변경 */
color: white; /* 마우스 호버 시 텍스트를 흰색으로 변경 */
    }

    .btn-password-edit {
        position: absolute;
    right: 0px; /* 사이드 바 버튼과의 거리 조절 */
   
    top: 400px;   /* 사이드 바 버튼과의 거리 조절 */
    width: 200px; /* 버튼 너비 */
        height: 50px; /* 버튼 높이 */
    background-color: #111;
    color: white;
    display: flex;
    justify-content: center; 
    align-items: center;
    padding: 10px 20px;
    border: none;
    cursor: pointer;
    z-index: 1002; /* 새 글 작성 버튼 위에 위치하도록 z-index 값을 높임 */
    box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;
    }

    .btn-password-edit:hover {
        background-color: mediumaquamarine; /* 마우스 호버 시 배경색을 검정색으로 변경 */
color: white; /* 마우스 호버 시 텍스트를 흰색으로 변경 */
    }
    .container {
  display: flex; /* Flexbox 사용 */
  justify-content: center; /* 가로축 중앙 정렬 */
  align-items: center; /* 세로축 중앙 정렬 */
}
</style>
<style>
    body {
    background-color: mediumturquoise;
}
</style>

<div class="container">
    <div style="margin-top: 10rem !important;">
        <div class="col-12">
            <div class="row justify-content-center">
                <div class="card">
                    <div class="card-header" style="padding-bottom: 8px;">
                        <strong style="font-size: 18px;"><i class="fas fa-user-cog"></i>&nbsp;&nbsp;내 정보</strong>
                    </div>
                    <div class="card-body">
                        <table class="table" style="color:black; margin-left:10px;">
                            <tr>
                                <td class="profile_title">아이디</td>
                                <td class="profile_content">{{ user.user_id }}</td>
                            </tr>
                            <tr>
                                <td class="profile_title">이메일</td>
                                <td class="profile_content">{{ user.email }}</td>
                            </tr>
                            <tr>
                                <td class="profile_title">이름</td>
                                <td class="profile_content">{{ user.name }}</td>
                            </tr>
                            <tr>
                                <td class="profile_title">닉네임</td>
                                <td class="profile_content">{{ user.nickname }}</td>
                            </tr>
                        </table>
                        <hr>
                        <div id="button-container" style="text-align: center;"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    // 버튼 생성 함수
    function createButton(iconClass, text, url, buttonClass) {
        var button = document.createElement("button");
        button.classList.add("btn", buttonClass); // 지정된 버튼 클래스 추가
        button.style.fontSize = "15px";

        var icon = document.createElement("i");
        icon.classList.add("fas", iconClass);
        button.appendChild(icon);
        button.innerHTML += "&nbsp;" + text;

        button.addEventListener("click", function() {
            window.location.href = url;
        });

        return button;
    }
    
     // 버튼 컨테이너
     var buttonContainer = document.getElementById("button-container");

// 내 정보 수정 버튼 생성
var profileUpdateButton = createButton("fa-user-edit", "내 정보 수정", "{% url 'user_inform:profile_update' %}", "btn-profile-update");
buttonContainer.appendChild(profileUpdateButton);

// 비밀번호 변경 버튼 생성
var passwordEditButton = createButton("fa-user-lock", "비밀번호 변경", "{% url 'user_inform:password_edit' %}", "btn-password-edit");
buttonContainer.appendChild(passwordEditButton);
</script>

{% endblock %}

templates/user_inform/modifyinform.html
{% extends 'base.html' %}

{% block content %}
<head>
    <title>내 정보 수정</title>
</head>

<style>
    .body {
        background-color: mediumturquoise;
    }
    
    .table {
        margin-bottom: 0;
    }
    
    hr {
        margin-top: 40px;
        margin-bottom: 40px;
        border: 0;
    }
    
    .card-body {
        background-color: #fff;
        padding: 20px;
        border-radius: 10px; 
    }
    
    .card-header {
            background-color: whitesmoke;
            border-bottom: 5px solid whitesmoke;
            padding-top: 14px;
            border-radius: 10px;
        }
    
    .card {
      width: 600px;
      height: auto;
      padding: 0;
      box-shadow: 0 4px 20px rgba(0, 0, 0, 0.2);
      border-radius: 10px;
    }
    
        .profile_title {
            font-weight: bold;
            color: black;
           
        }
    
        .profile_content {
            color: #666;
        }
    
        .btn-sm {
            position: absolute;
    right: 490px; /* 사이드 바 버튼과의 거리 조절 */
   
    top: 300px;   /* 사이드 바 버튼과의 거리 조절 */
    /* left: 500px; */
        width: 100px; /* 버튼 너비 */
        height: 40px; /* 버튼 높이 */
    background-color: #111;
    color: white;
    display: flex;
    justify-content: center; 
    align-items: center;
    padding: 10px 20px;
    border: none;
    cursor: pointer;
    z-index: 1002; /* 새 글 작성 버튼 위에 위치하도록 z-index 값을 높임 */
    box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;
      }
      
    
        .btn-sm:hover {
            background-color: mediumaquamarine;
            color: white;
        }
    
        .btn-sm1 {
            position: absolute;
    right: 10px; /* 사이드 바 버튼과의 거리 조절 */
   
    top: 300px;   /* 사이드 바 버튼과의 거리 조절 */
    /* left: 900px; */
        width: 100px; /* 버튼 너비 */
        height: 40px; /* 버튼 높이 */
    background-color: #111;
    color: white;
    display: flex;
    justify-content: center; 
    align-items: center;
    padding: 10px 20px;
    border: none;
    cursor: pointer;
    z-index: 1002; /* 새 글 작성 버튼 위에 위치하도록 z-index 값을 높임 */
    box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;
      }
      
    
        .btn-sm1:hover {
            background-color: mediumaquamarine;
            color: white;
        }
        .container {
      display: flex; /* Flexbox 사용 */
      justify-content: center; /* 가로축 중앙 정렬 */
      align-items: center; /* 세로축 중앙 정렬 */
    }
    </style>
    
<style>
        body {
        background-color: mediumturquoise;
    }
    </style>
    <style>
        input[type="text"] {
  width: 100%; /* 폭을 조정합니다. 예: 50%, 300px */
  padding: 0; /* 내부 여백을 조정합니다. */
  margin-left: 10px;
  margin-bottom: 5px; /* 아래쪽 마진을 조정합니다. */
  border: 1px solid #CED4DA; /* 테두리 스타일을 조정합니다. */
  border-radius: 3px; /* 테두리 모서리를 둥글게 조정합니다. */
  box-sizing: border-box; /* 너비와 높이 계산 방식을 조정합니다. */
  font-size: 16px; /* 글꼴 크기를 조정합니다. */
}
    </style>
    
<div class="container">
    
    <div style="margin-top: 13rem !important;">
        <div class="col-12">

            <div class="row justify-content-center">
                <div class="card">
                    <div class="card-header" style="padding-bottom:8px;">
                        <strong style="font-size: 18px;"><i class="fas fa-user-edit"></i>&nbsp;&nbsp;내 정보 수정</strong>
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            <table style="color:black; margin-left:10px;">
                                <tr>
                                    <td class="profile_title">아이디</td>
                                    <td class="profile_content">&nbsp;&nbsp;{{ user.user_id }}</td>
                                </tr>
                                <tr>
                                    <td class="profile_title">이메일</td>
                                    <td class="profile_content">&nbsp;&nbsp;{{ user.email }}</td>
                                </tr>
                                <tr>
                                    <td class="profile_title">이름</td>
                                    <td class="profile_content">{{ user_change_form.name }}</td>
                                </tr>
                                <tr>
                                    <td class="profile_title">닉네임</td>
                                    <td class="profile_content">{{ user_change_form.nickname }}</td>
                                </tr>
                            </table>
                            <br>
<<<<<<< HEAD
                            <div style="text-align: center; ">
                                <a onclick="location.href='/user_inform'" class="btn btn-sm" id="back_btn"><i class="fa fa-reply"></i>&nbsp;뒤로</a>
                                <button type="submit" class="btn btn-sm1" id="detail_btn"><i class="fas fa-check"></i>&nbsp;수정</button>
=======
                            <div style="text-align: center; margin-bottom:-15px;">
                                <a onclick="location.href='/user-inform/information/'" class="btn btn-sm" id="back_btn"><i class="fa fa-reply"></i>&nbsp;돌아가기</a>
                                <button type="submit" class="btn btn-sm" id="detail_btn"><i class="fas fa-check"></i>&nbsp;수정하기</button>
>>>>>>> b9fde118869f984522fa7a3203fdb66bdfcead7a
                            </div>
                        </form>
                        
                        <script type = "text/javascript">
                            function maxLengthCheck(object){
                                if (object.value.length > object.maxLength) {
                                    object.value = object.value.slice(0, object.maxLength);
                                    }   
                                }
                        </script>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/user_inform/modifypw.html
{% extends 'base.html' %}
{% block content %}
<head>
    <title>비밀번호 변경</title>
</head>
<style>
    .body {
        background-color: mediumturquoise;
    }
    
    .table {
        margin-bottom: 0;
    }
    
    hr {
        margin-top: 40px;
        margin-bottom: 40px;
        border: 0;
    }
    
    .card-body {
        background-color: #fff;
        padding: 20px;
        border-radius: 10px; 
    }
    
    .card-header {
            background-color: whitesmoke;
            border-bottom: 5px solid whitesmoke;
            padding-top: 14px;
        }
    
    .card {
      width: 600px;
      height: auto;
      padding: 0;
      box-shadow: 0 4px 20px rgba(0, 0, 0, 0.2);
      border-radius: 10px;
    }
    
        .profile_title {
            font-weight: bold;
            color: black;
           
        }
    
        .profile_content {
            color: #666;
        }
    
        .btn-sm {
            position: absolute;
    right: 390px; /* 사이드 바 버튼과의 거리 조절 */
   
    top: 400px;   /* 사이드 바 버튼과의 거리 조절 */
    /* left: 500px; */
        width: 100px; /* 버튼 너비 */
        height: 35px; /* 버튼 높이 */
    background-color: #111;
    color: white;
    display: flex;
    justify-content: center; 
    align-items: center;
    padding: 10px 20px;
    border: none;
    cursor: pointer;
    z-index: 1002; /* 새 글 작성 버튼 위에 위치하도록 z-index 값을 높임 */
    box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;
      }
      
    
        .btn-sm:hover {
            background-color: mediumaquamarine;
            color: white;
        }

        .btn-sm1 {
            position: absolute;
    right: 00px; /* 사이드 바 버튼과의 거리 조절 */
   
    top: 400px;   /* 사이드 바 버튼과의 거리 조절 */
    /* left: 900px; */
        width: 100px; /* 버튼 너비 */
        height: 35px; /* 버튼 높이 */
    background-color: #111;
    color: white;
    display: flex;
    justify-content: center; 
    align-items: center;
    padding: 10px 20px;
    border: none;
    cursor: pointer;
    z-index: 1002; /* 새 글 작성 버튼 위에 위치하도록 z-index 값을 높임 */
    box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;
      }
      
    
        .btn-sm1:hover {
            background-color: mediumaquamarine;
            color: white;
        }
    
        .container {
      display: flex; /* Flexbox 사용 */
      justify-content: center; /* 가로축 중앙 정렬 */
      align-items: center; /* 세로축 중앙 정렬 */
    }
    </style>

<style>
    body {
    background-color: mediumturquoise;
}
</style>

<div class="container">
    <div style="margin-top: 10rem !important;">
        <div class="col-12">

            <div class="row justify-content-center">
                <div class="card" style="width: 500px;">
                    <div class="card-header" style="padding-bottom:8px;">
                        <strong style="font-size: 18px;"><i class="fas fa-user-lock"></i>&nbsp;&nbsp;비밀번호 변경</strong>
                    </div>
                    <div class="card-body">
                                            
                        <form method="POST" novalidate>
                            {% csrf_token %}
                            <!-- {{ password_change_form.as_p }} -->

                            <!-- {% for field in password_change_form %} -->
                            <!-- <div class="form group">
                                <div class="mb-4 md-form">
                                <label for="{{ field.id_for_label }}"><i class="fas fa-lock"></i>&nbsp;{{ field.label|cut:":" }}</label>
                                <input type="{{ field.field.widget.input_type }}" class="form-control"
                                    id="{{ field.id_for_label }}" name="{{ field.name }}">
                                </div>
                            </div> -->

                            <!-- <div class="form group">
                                <label for="{{ field.id_for_label }}"><i class="fas fa-lock"></i>&nbsp;{{ field.label|cut:":" }}</label>
                                <input type="{{ field.field.widget.input_type }}" class="form-control"
                                    id="{{ field.id_for_label }}" name="{{ field.name }}"
                                    placeholder="{{ field.label|cut:':' }}" />
                            </div><br> -->
                            <!-- {{ field.errors }} -->
                            <!-- {% endfor %} -->

                            <!-- <style>
                                .errorlist {
                                    color: red;
                                    font-weight: bold;
                                }
                            </style> -->

                            <!--기존 비밀번호-->
                            <div class="mb-4 md-form">
                                
                                <label name="label_old_password" for="{{ password_change_form.old_password.id_for_label }}"><i
                                        class="fas fa-lock"></i>&nbsp;&nbsp;{{ password_change_form.old_password.label }}</label>
                                {{ password_change_form.old_password }}
                                <script type="text/javascript">
                                    if (document.getElementsByName('old_password')[0].value != '') {
                                        document.getElementsByName('label_old_password')[0].setAttribute('class',
                                            'active');
                                    }
                                </script>
                                {% if password_change_form.old_password.errors %}
                                <script type="text/javascript">
                                    document.getElementsByName('old_password')[0].setAttribute('class',
                                        'form-control is-invalid')
                                </script>
                                {% for error in password_change_form.old_password.errors %}
                                <div class="invalid-feedback" style="margin-bottom:-10px;">
                                    {{ error }}
                                </div>
                                {% endfor %}
                                {% endif %}
                            </div>
                            <!--새 비밀번호-->
                            <div class="mb-4 md-form">
                                <label name="label_new_password1" for="{{ password_change_form.new_password1.id_for_label }}"><i
                                        class="fas fa-unlock"></i>&nbsp;&nbsp;{{ password_change_form.new_password1.label }}</label>
                                {{ password_change_form.new_password1 }}
                                <script type="text/javascript">
                                    if (document.getElementsByName('new_password1')[0].value != '') {
                                        document.getElementsByName('label_new_password1')[0].setAttribute('class',
                                            'active');
                                    }
                                </script>
                                {% if password_change_form.new_password1.errors %}
                                <script type="text/javascript">
                                    document.getElementsByName('new_password1')[0].setAttribute('class',
                                        'form-control is-invalid')
                                </script>
                                {% for error in password_change_form.new_password1.errors %}
                                <div class="invalid-feedback" style="margin-bottom:-10px;">
                                    {{ error }}
                                </div>
                                {% endfor %}
                                {% endif %}
                            </div>
                            <!--새 비밀번호확인-->
                            <div class="mb-4 md-form">
                                <label name="label_new_password2" for="{{ password_change_form.new_password2.id_for_label }}"><i class="fas fa-unlock-alt"></i>&nbsp;&nbsp;{{ password_change_form.new_password2.label }}</label>
                                
                                <input type="password" class="form-control" name="{{ password_change_form.new_password2.name }}" placeholder="최소 8개의 숫자와 문자 또는 특수기호를 입력해주세요">
                                
                                <script type="text/javascript">
                                    var inputField = document.getElementsByName('{{ password_change_form.new_password2.name }}')[0];
                                    var labelField = document.getElementsByName('label_new_password2')[0];
                            
                                    inputField.addEventListener('input', function() {
                                        if (inputField.value !== '') {
                                            labelField.setAttribute('class', 'active');
                                        } else {
                                            labelField.setAttribute('class', '');
                                        }
                                    });
                                </script>
                                
                                {% if password_change_form.new_password2.errors %}
                                <script type="text/javascript">
                                    document.getElementsByName('{{ password_change_form.new_password2.name }}')[0].setAttribute('class', 'form-control is-invalid');
                                </script>
                                
                                {% for error in password_change_form.new_password2.errors %}
                                <div style="white-space: nowrap;" class="invalid-feedback">
                                    {{ error }}
                                </div>
                                {% endfor %}
                                {% endif %}
                                
                            </div>
                            <div style="text-align: center; margin-bottom:-10px;">
                                <p style="color:gray; margin-top: 20px;"><i class="fas fa-exclamation-triangle"></i>&nbsp;{{ user.user_id }} 계정의 비밀번호를 변경합니다.</p>
                                <a onclick="location.href='/user_inform/'" class="btn btn-sm" id="back_btn"><i class="fa fa-reply"></i>&nbsp;뒤로</a>
                                <button type="submit" class="btn btn-sm1" id="detail_btn"><i class="fas fa-check"></i>&nbsp;변경</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}