accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
   #path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
   path('login/', views.LoginView.as_view(), name='login'),
   path('logout/',views.logout_view,name='logout') ,
   path('signup/', views.CsRegisterView.as_view(), name='signup'),
   path('check_user_id/', views.check_user_id_view, name='check_user_id'),
]

board/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'board'

urlpatterns = [
    path('create_board/', views.board, name='create_board'),
    path('board_detail/<int:board_id>/', views.read, name='board_detail'),
    path('board_edit/<int:pk>', views.boardEdit, name='edit'),
    path('delete/<int:pk>', views.boardDelete, name='delete'),
    path('comment_create/<int:pk>/', views.comment_create, name='comment_create'),
    path('comments/<int:board_pk>/delete/<int:comment_pk>/', views.comment_delete, name='comments_delete'),   
    path('board_list/', views.boardList, name = 'board_list'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from homemain import views

urlpatterns = [
    path('admin/', admin.site.urls) ,
    path('accounts/', include('accounts.urls')) ,
    path('user_inform/', include('user_inform.urls')) ,
    path('board/', include('board.urls')) ,
    path('index/', views.index, name='index'),  # '/' 에 해당되는 path
    #path('board_list/', views.boardList),
]

user_inform/urls.py
from django.urls import path
from . import views

app_name = 'user_inform'

urlpatterns = [
   #path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('',views.information,name='information') ,
    path('modifyinform/',views.profile_update_view, name='profile_update') ,
    path('modifypw/',views.password_edit_view, name='password_edit') ,
]

templates/base.html
{% load static %}

<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Security arXiv</title>
    <link rel="icon" href="image/png" href="securee.png" />

</head>

<body>
<!-- 네비게이션바 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
</body>
</html>

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors%}
    <div>
        <label>아이디 또는 비밀 번호가 맞지 않습니다. 다시 확인해주세요.</label>
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <label>아이디 또는 비밀 번호가 맞지 않습니다. 다시 확인해주세요.</label>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/navbar.html
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="style.css">
    <style>
        @import url('https://fonts.googleapis.com/css?family=Rubik&display=swap');

        body {
            margin: 0;
            background: mediumturquoise;
        }

        .sidebar {
            position: fixed;
            width: 250px;
            top: 0;
            left: -265px;
            bottom: 0;
            background: #111;
            padding-top: 50px;
            transition: 0.4s;
            height: 85%;
            margin: auto 10px;
            border-radius: 12px;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        }

        .sidebar h1 {
            display: block;
            padding: 10px 20px;
            color: mediumaquamarine;
            text-decoration: none;
            font-family:Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif;
            font-weight: 400;
            margin: 0;
            font-size: 20px;
        }

        .sidebar a {
            display: block;
            padding: 10px 20px;
            color: #bbb;
            text-decoration: none;
            font-family: "Rubik";
            letter-spacing: 2px;
        }

        .sidebar a:hover {
            color: #fff;
            margin-left: 20px;
            transition: 0.4s;
        }

        button {
            position: fixed;
            right: 30px;
            top: 30px;
            background: #111;
            padding: 10px;
            border-radius: 2px;
            outline: none;
            border: none;
            border-radius: 50%;
            cursor: pointer;
            box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;
        }
        

        button span {
            height: 3px;
            width: 20px;
            display: block;
            margin: 6px;
            background: #FFF;
        }

        

        .show {
            left: 0;
        }

        .credit {
            position: fixed;
            left: 40%;
            bottom: 0;
            color: #000;
            padding-bottom: 5px;
            font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
        }

        .credit > a {
            text-decoration: none;
            color: white;
        }
    </style>
    <style>
        /* Footbar 스타일 */
        .footbar {
            background-color: #000;
            color: #fff;
            text-align: center;
            padding: 10px 0;
            position: fixed;
            bottom: 0;
            width: 100%;
            z-index: 1000; /* 다른 요소 위에 나타나도록 설정 */
        }

        
    </style>
</head>
<body>
    <div class="sidebar" id='sidebar'>
        <h1>Secure arXiv</h1>
        <a href="{% url 'homemain:index' %}">Home</a>
        {% if user.is_authenticated %}
        <a class="text">Welcome {{ user.name }}님!</a>
        <a href="{% url 'board:board_list' %}">Site</a>
        <a href="{% url 'user_inform:information' %}">Profile</a>
        <a href="{% url 'accounts:logout' %}">Logout</a>
        {% else %}
        <a href="{% url 'accounts:login' %}">login</a>
        {% endif %}
    </div>

    <button onclick='showSidebar()'>
        <span></span>
        <span></span>
        <span></span>
    </button>

   

    <!-- Footbar -->
    <div class="footbar">
        Copyright © 2024 Security arXiv. All Rights Reserved.
    </div>

    <script>
        function showSidebar() {
            var x = document.getElementById('sidebar');
            if (x.className === "sidebar") {
                x.className += " show";
            } else {
                x.className = "sidebar";
            }
        }
    </script>
    <script>
         document.addEventListener('DOMContentLoaded', function () {
        var newPostButton = document.querySelector('.new-post-button');
        
        newPostButton.addEventListener('click', function (event) {
            event.stopPropagation(); // 이벤트 전파 중지
        });
    });
    </script>
</body>
</html>
<!--<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'homemain:index' %}">InfoSec</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link " >{{ user.name }}님</a>
                    </li>    
                    <li class="nav-item">
                        <a class="nav-link " href="{% url 'accounts:logout' %}">로그아웃</a>
                    </li>                
                    <li class="nav-item">
                        <a class="nav-link"  href="{% url 'user_inform:information' %}">마이페이지</a>
                    </li>  
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
                    </li>
                    {% endif %}
                </li>
            </ul>
        </div>
        
        
        
    </div>
</nav>-->